joint_limit: [ '0.002', '5.890' ,
               '0.002', '2.695' ,
               '-5.148', '-0.01',
               '0.009', '3.598' ,
               '0.05', '5.864' ,
               '0.00', '1.00',
               '0.00', '1.00']

