map_type: costmap
transform_tolerance: 0.3
obstacle_range: 4.0
raytrace_range: 3.0
inflation_radius: 0.25

#obstacles:
observation_sources: base_scan_front base_scan_rear front_barrier rear_barrier
#observation_sources: front_barrier rear_barrier

base_scan_front: {sensor_frame: base_laser_front_link,
          data_type: LaserScan,
          topic: /base_scan_front,
          expected_update_rate: 0.4,
          observation_persistence: 0.0,
          marking: true,
          clearing: true,
          min_obstacle_height: -0.10,
          max_obstacle_height: 2.0}

base_scan_rear: {sensor_frame: base_laser_rear_link,
          data_type: LaserScan,
          topic: /base_scan_rear,
          expected_update_rate: 0.4,
          observation_persistence: 0.0,
          marking: true,
          clearing: true,
          min_obstacle_height: -0.10,
          max_obstacle_height: 2.0}
 
front_barrier: {sensor_frame: front_barrier_link,
          data_type: PointCloud,
          topic: /youbot_barrier_front_detection/PublishPointCloud/output,
          marking: true,
          clearing: true}

rear_barrier: {sensor_frame: rear_barrier_link,
          data_type: PointCloud,
          topic: /youbot_barrier_rear_detection/PublishPointCloud/output,
          marking: true,
          clearing: true}
 
