#change this
#old one laser forward and backward

footprint: [
             [-0.285,-0.195],
             [-0.285,-0.05],
             [-0.324,-0.05],
             [-0.324,0.05],
             [-0.285,0.05],
             [-0.285,0.195],
             [0.285,0.195],
             [0.285,0.05],
             [0.324,0.05],
             [0.324,-0.05],
             [0.285,-0.05],
             [0.285,-0.195]
           ]

#footprint: [
#             [0.28, 0.19],
#             [-0.28, 0.19],
#             [-0.28, -0.19], 
#             [0.28, -0.19]
#           ]

#new one laser forward and backward, arm extension with wings


#footprint: [
#            [0.30, 0.19],
#            [0.30, 0.101],
#            [0.374, 0.101],
#            [0.374, -0.101], 
#            [0.307, -0.101], 
#            [0.351, -0.215], 
#            [0.310, -0.255], 
#            [0.212, -0.19],
#            [-0.30, -0.19],
#            [-0.30, -0.101],
#            [-0.374, -0.101],
#            [-0.374, 0.101], 
#            [-0.307, 0.101], 
#            [-0.351, 0.215], 
#            [-0.310, 0.255], 
#            [-0.212, 0.19],
#           ]

controller_frequency: 20.0
controller_patience: 15.0
clearing_radius: 0.6
footprint_padding: 0.05
clearing_rotation_allowed: true
recovery_behavior_enabled: true
