recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aricc_move_slow_and_clear'
    type: 'move_slow_and_clear/MoveSlowAndClear'
#  - name: 'local_move_recovery'
 #   type: 'local_move_recovery/LocalMoveRecovery'

#TODO:create custom recovery behavior

#super_conservative_reset:
#  reset_distance: 5.0

conservative_reset:
  reset_distance: 0.8

aggressive_reset:
  reset_distance: 0.3

aricc_move_slow_and_clear:
  clearing_distance: 0.65
  limited_x_speed: 0.25
  limited_y_speed: 0.25
  limited_theta_speed: 0.45
  limited_distance: 0.3

local_move_recovery:
  frequency: 20.0
  sim_time: 1.5
  target_dist: 1.0
  max_vel_x: 0.3
  min_vel_x: -0.3
  max_vel_y: 0.3
  min_vel_y: -0.3
  max_vel_th: 0.3
  min_vel_th: -0.3  
  vx_samples: 2
  vy_samples: 2
  vtheta_samples: 2

 
