arm_joints_unload_table:       [ '2.15', '1.90', '-1.30', '2.95', '2.95' ]
arm_joints_look_table_left:    [ '1.37', '2.02', '-2.14', '0.42', '2.95' ]
#arm_joints_look_table:         [ '2.15', '1.35', '-1.07', '0.03', '2.95' ]
arm_joints_look_table:         [ '2.15', '1.04', '-1.39', '3.40', '2.95' ]
arm_joints_look_table_right:   [ '2.95', '2.02', '-2.14', '0.42', '2.95' ]
arm_joints_transport:          [ '2.15', '0.03', '-0.03', '0.03', '2.95' ]
arm_joints_standby:            [ '1.77', '1.04', '-1.39', '2.90', '2.95' ]
#arm_joints_standby:            [ '2.15', '0.40', '-1.20', '3.00', '2.95' ]

arm_joints_ready_tray_left:    [ '2.77', '0.50', '-3.12', '0.12', '3.32' ]
arm_joints_tray_left:          [ '2.73', '0.11', '-2.94', '0.15', '3.30' ]

#arm_joints_ready_tray_center: [ '2.93', '1.00', '-3.30', '0.05', '2.92' ]
arm_joints_ready_tray_center:  [ '2.37', '0.59', '-3.32', '0.07', '3.07' ]
arm_joints_before_tray_center: [ '2.37', '0.59', '-3.32', '0.07', '3.07' ]
arm_joints_tray_center:        [ '2.37', '0.39', '-3.48', '0.39', '3.09' ]

arm_joints_ready_tray_right:   [ '1.57', '0.60', '-3.27', '0.26', '2.56' ]
arm_joints_tray_right:         [ '1.61', '0.23', '-3.22', '0.34', '2.52' ]

#gripper_open:                 [ '0.03', '0.03' ]
#gripper_close:                [ '0.00', '0.00' ]
gripper_open:                  [ '1', '1' ]
gripper_close_light:           [ '0.0', '0.0' ]
gripper_close_heavy:           [ '0.0', '0.0' ]


arm_joints_ready_cut:   [ '2.11', '0.81', '-1.75', '1.76', '2.95' ]
arm_joints_cut:         [ '2.15', '0.80', '-1.91', '2.84', '2.95' ]
arm_joints_plaque:      [ '2.07', '0.27', '-0.49', '0.88', '2.93' ]
arm_joints_transport_p: [ '2.07', '0.19', '-0.04', '0.60', '2.95' ]
arm_joints_pass_plaque: [ '2.07', '1.12', '-1.62', '1.36', '2.97' ]
