objects:
  - {name: 'F20_20',   width: '0.033', height: '0.117', color: '145'}
  - {name: 'S40_40',   width: '0.059', height: '0.107', color: '160'}
#  - {name: 'M20_100',  width: '0.050', height: '0.122', color: '122'}
#  - {name: 'M20_100',  width: '0.047', height: '0.107', color: '130'}
  - {name: 'M20',      width: '0.048', height: '0.052', color: '132'}
  - {name: 'M30',      width: '0.058', height: '0.064', color: '155'}
  - {name: 'R20',      width: '0.015', height: '0.103', color: '136'}
#  - {name: 'V20',      width: '0.046', height: '0.060', color: '-1'}

