locations:
  - {place: 'Shelf 1', x: '-4.0038',  y: '-1.9906',  z: '0', dir: 'WEST', align: '0.075', height: '0.10'}
  - {place: 'Shelf 2', x: '-4.0038',  y: '-1.9906',  z: '0', dir: 'WEST', align: '0.075', height: '0.10'}

##################################WAYPOINTS#################################

  - {place: 'Waypoint 1', x: '-0.41325',  y: '-0.89213',  z: '0', dir: 'NORTH', align: '0.08', height: '0.05'}
  - {place: 'Waypoint 2', x: '-3.2108',  y: '-2.0983',  z: '0', dir: 'NORTH', align: '0.1', height: '0.05'}
  - {place: 'Waypoint 3', x: '-2.1204', y: '-1.9432',  z: '0', dir: 'NORTH', align: '0.1', height: '0.05'}
  - {place: 'Waypoint 4', x: '-1.5434', y: '-2.2494',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 5', x: '-1.2413', y: '-1.7504',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 6',  x: '-3.2346', y: '-1.3018', z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 7', x: '-0.65851', y: '-1.6706', z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 8', x: '0.30842', y: '-2.807', z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 9', x: '-0.4445',  y: '-3.5184',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 10', x: '-0.93565', y: '-1.3037',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 11', x: '-0.27459', y: '-1.9873',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 12', x: '-1.0018', y: '-3.5781',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 13', x: '-1.796', y: '-3.5781',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 14', x: '-3.0603', y: '-2.8764',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}
  - {place: 'Waypoint 15', x: '-0.85874', y: '-2.117',  z: '0', dir: 'NORTH', align: '0.075', height: '0.05'}

############################WORKSTATIONS###############################

  - {place: 'Workstation 1', x: '-0.5068',  y: '-1.1298',  z: '0', dir: 'NORTH', align: '0.075', height: '0.10'}
  - {place: 'Workstation 2', x: '0.4486', y: '-2.8509',  z: '0', dir: 'EAST', align: '0.075', height: '0.10'}
  - {place: 'Workstation 3', x: '-0.52991',  y: '3.5789',  z: '0', dir: 'WEST', align: '0.075', height: '0.10'}
  - {place: 'Workstation 4', x: '0.8554', y: '-2.0659',  z: '0', dir: 'EAST', align: '0.075', height: '0.10'}
  - {place: 'Workstation 5', x: '-1.5988',  y: '-1.6497',  z: '0', dir: 'WEST', align: '0.075', height: '0.05'}
  - {place: 'Workstation 6', x: '-1.4876', y: '-2.9111',  z: '0', dir: 'SOUTH', align: '0.075', height: '0.10'}
  - {place: 'Workstation 7', x: '-0.52991',  y: '3.5789',  z: '0', dir: 'WEST', align: '0.075', height: '0.10'}
  - {place: 'Workstation 8', x: '-0.5068',  y: '-1.1298',  z: '0', dir: 'NORTH', align: '0.075', height: '0.10'}
  - {place: 'Workstation 9', x: '-1.4876', y: '-2.9111',  z: '0', dir: 'SOUTH', align: '0.075', height: '0.10'}
  - {place: 'Workstation 10', x: '-1.5988',  y: '-1.6497',  z: '0', dir: 'WEST', align: '0.075', height: '0.05'}
  - {place: 'Workstation 11', x: '0.4486', y: '-2.8509',  z: '0', dir: 'EAST', align: '0.075', height: '0.10'}
  - {place: 'Workstation 12', x: '-0.8554', y: '-2.0659',  z: '0', dir: 'EAST', align: '0.075', height: '0.10'}

  - {place: 'Rotating Table', x: '-1.2883',  y: '-3.6427',  z: '0', dir: 'SOUTH', align: '-1', height: '0.10'}
  - {place: 'Conveyor Belt', x: '-3.3989',  y: '-2.5598',  z: '0', dir: 'SOUTH', align: '-1', height: '0.10'}
  - {place: 'Robot', x: '-1.5719',  y: '-3.4815',  z: '0', dir: 'NORTH', align: '0.075', height: '0.0'}
  - {place: 'Precision Platform', x: '-0.37035',  y: '-1.9695',  z: '0', dir: 'NORTH', align: '0.075', height: '0.10'}

  - {place: 'Exit', x: '-3.1708', y: '-2.4832',  z: '0', dir: 'WEST', align: '0.075', height: '0.0'}
